### ISSUE TITLE
Incorrect Version: Parent Version is considered instead of artefact version

### ISSUE THREAD

**Issue by dishantkamble** [nnichols/maven-version-bump-action#5]
# Incorrect Version

## Description

My current artefact version is 1.0.1 whereas my spring-boot-starter-parent version is 2.4.2. The action is considering the current version of my artefact as 2.4.2 instead of 1.0.1

### Expected Behavior

The action should consider the current version of my artefact as 1.0.1 instead of 2.4.2

**Comment by nnichols** [comment]
Thanks for letting me know! 

I've identified the root cause (grepping for the project version) and I think I have a fix close. I'll get it tested out and report back

**Comment by nnichols** [comment]
@dishantkamble I've tested this commit `c1c1e19b652ccda58613d48464730b16b16fe46a` with a repo that had a reordered pom.xml, and was able to bump successfully. I'll be merging and releasing v4 shortly

Related PR: https://github.com/nnichols/maven-version-bump-action/pull/6
